name: todo_app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_splash_screen: ^1.1.0
  # firebase integration
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1

  # slidable
  flutter_slidable: ^0.5.7

  # state management
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo6.png"

  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "ToDo List"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

